---
title: How We Plan a Podcast Season
author: Larry Vincent
date: 2019-02-17
slug: how-we-plan-a-podcast-season
draft: true
categories:
  - Podcasting
tags:
  - podcasting
  - writing
  - creativity
---
The long holiday weekend provided me the opportunity to start work on the next season of _The Findings Report_, the podcast that I produce with Molly Schreiber. If you haven't listed in, the show is a deep dive on consumer psychology. Each episode examines why people buy, like and share through the lens of a specific behavioral trend. Ok, enough with the plug. Back to my long weekend work.

We produce the show in a seasonal format. The episodes aren't episodic, but because the show is a hobby, and not my full-time job, seasons help us create and deliver content in batches. We drop a new show every week over the course of nine consecutive weeks. We've found this format streamlines our production process, which I thought I would share here for others who might be thinking about producing a podcast of their own.

# Story Planning
Arguably, one of the hardest parts of the process is the first few weeks. During that time we create a long list of show ideas. Molly and I each share thoughts through numerous email exchanges. Last season, we also collaborated with my colleagues Valerie Cabrera Krause and Grady Lopez. This season, we took it one step further and organized a brainstorming lunch to pitch and discuss our various ideas.

The process is tricky because our show aims for a degree of journalistic rigor. We're not a talking heads show. It isn't Molly and I in a room riffing on whatever is on our mind. Instead, every show is a carefully orchestrated mix of interviews with expert guests, sound bites from popular culture and heard-on-the-street interviews with real consumers. In the planning phase, we pitch ideas that interest us but we also add the mandate that there needs to be some nugget of insight that validates its importance to listeners. That could be a new book by an expert, or a piece of research, or a demonstrable trend that's backed by data. For every episode, we try to ensure we have satisfied the following five criteria:

- Is it 