theme: "hugo-zen"
baseURL: http://brandnerd.io/
languageCode: en-us
title: Brand Nerd
author: Larry Vincent
draft: true
copyright: 2019 by Laurence Vincent
menu:
  main:
  - identifier: about
    name: about
    url: "/about"
params:
  logo: "/images/brandnerd.jpg"
  twitter: "https://www.twitter.com/lvincent"
  github: "https://www.github.com/larryvincent"
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
