---
title: "Purpose"
author: "Larry Vincent"
date: 2019-01-20
summary: "On why I started this blog and what I hope to post here in the future."
categories:
  - Meta
  - Branding
tags: 
  - essays
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE)
```

I believe I was once quoted saying, "I need another blog like I need a hole in my head." I don't quite recall where that was quoted or by whom, but the sentiment is true. I have a couple of blogs. So, why start another?

The answer could easily be, "because I can." But it's a little more nuanced than that. The truth is that I feel boxed in by my current blogs. 

I am quite proud of [The Findings Report](http://www.findingsreport.com), my blog and podcast that focuses on consumer psychology. It exists to answer why people buy, like and share. It has been several months since I wrote anything there. I took a break in March that was supposed to last for a few weeks. It then expanded into a summer hiatus. And now it can only be described as desertion. I will write there again, but it's a difficult process. It is a more formal channel, painstakingly designed to have a curated, editorial feel. It is also linked to a newsletter that I am reticent to tax with random bits. I feel the pressure to make every blog post something meaty. That takes a toll after a while.

[Jordan's Journey](http://www.jordansjourney.com) is a labor of love. I have been writing it off and on since 2004. But it is very specific. It is a living memoir of my daughter's journey with brain cancer. It began as a communication vehicle to friends and family but it quickly became an emotional outlet--the one place where I could unpack the emotions I was experiencing as I watched my _cancer slayer_ battle a debilitating disease. Again, not a blog for miscellaneous discoveries and essays.

I have been craving a less formal venue--a place to share what I learn as a strategist, a researcher, a teacher, and as a human. This blog is a sandbox. I am purposefully not spending much time on its design. You'll be unlikely to find the snazzy images you'd find on _The Findings Report_. But you will probably see some tables and graphs because this sandbox is for data. In some ways, this blog is a companion to _The Findings Report_. In others, it is a simply a collection of journal entries.

As I begin this blog, I am reminded of a passage from the great essayist, Michel Foucault:

> I don’t feel that it is necessary to know exactly what I am. The main interest in life and work is to become someone else that you were not in the beginning. If you knew when you began a book what you would say at the end, do you think that you would have the courage to write it? What is true for writing and for love relationships is true also for life. The game is worthwhile insofar as we don’t know where it will end.

And, with that somewhat precocious quotation, I begin a new journey. I hope you'll come along with me. And I welcome your feedback as I go.